Feature/jf UI 11276 performance
jfrog/jfrog-ui-essentials pull request #101
Opened 2022-11-03 09:33 UTC by tomerelkayam

2022-11-06 10:08 UTC, ur92 requested changes

2022-11-06 10:34 UTC, tomerelkayam commented on src/components/JfDataListComponent/JfDatalistItemComponent/index.vue
> +import { filter, extend, omit } from 'lodash'
I know, it will be applied in next phase

2022-11-06 10:34 UTC, tomerelkayam commented on src/components/JfListMakerComponent/index.vue
> +    import { find, isEmpty, sortBy } from "lodash";
I know, it will be applied in next phase

2022-11-06 10:57 UTC, tomerelkayam commented on package.json
> -    "moment": "^2.29.4",
No, it is not actually used anymore by ui-essentials

2022-11-06 10:58 UTC, tomerelkayam commented on src/components/JfDataListComponent/JfDatalistItemComponent/index.vue
> +            this.item.value = filter(this.item.value, valueItem => valueItem.label !== tag.label)
I don't want to effect the code more than I have to (lodash.filter is more safe since int knows how to handle empty arrays)

2022-11-07 18:55 UTC, tomerelkayam commented on src/components/JfListMakerComponent/index.vue
> +    import { find, isEmpty, sortBy } from "lodash";
Implemented

2022-11-13 10:56 UTC, merged